#!/usr/bin/env bash

set -euo pipefail
THISDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
test -f "$THISDIR/.env" && source "$THISDIR/.env"

function help(){
cat << EOF
uv-fasthtml

restore                         : Fetch dependencies
serve                           : Spawn a server
stop                            : Kill server
dev                             : Run the server without backgrounding
alembic                         : Run alembic
lint                            : Run linter
test <unit|integration|e2e|all> : Run tests, defaults to all
EOF
}

function run_restore(){
	uv sync
	uv run alembic upgrade head
}

function run_serve(){
	uv run app/main.py &
}

function run_stop(){
	port=${PORT:-5001}
	# By default the application runs on port 5001.
	# This command finds applications running on port 5001 and
	# kills them.
	lsof -i ":$port" | awk '{print $2}' | tail -n +2 | xargs kill
}

function run_dev(){
	uv run app/main.py
}

function run_alembic(){
	uv run alembic "$@"
}

function run_lint(){
	uv run ruff check
}

function run_unit(){
	TESTING=true uv run pytest tests/unit
}

function run_integration(){
	TESTING=true uv run pytest tests/integration
}

function run_e2e(){
	echo "Disabled pending rewrite."
	#uv run playwright install 
	#TESTING=true uv run pytest tests/e2e
}

function run_test(){
  scope=${1-all}
	case "$scope" in
		all)
			run_unit
			run_integration
			run_e2e
			;;
		unit)
			run_unit
			;;
		integration)
			run_integration
			;;
		e2e)
			run_e2e
			;;
		esac
}

function main(){
	cmd=${1-default}
	shift || true
	case "$cmd" in
		default|help)
			help "$@"
			;;
		restore)
			run_restore
			;;
		serve)
			run_serve
			;;
		stop)
			run_stop
			;;
		dev)
			run_dev
			;;
		alembic)
			run_alembic "$@"
			;;
		lint)
			run_lint
			;;
		test)
			run_test "$@"
			;;
		*)
			echo "no-op $cmd"
			;;
	esac
}

main "$@"
