#!/usr/bin/env bash

set -euo pipefail
THISDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

function help(){
cat << EOF
uv-fasthtml

help        : Display help text
restore     : Fetch dependencies
serve       : Spawn a server
stop        : Kill server
lint        : Run linter
unit        : Run unit tests
EOF
}

function run_restore(){
	uv sync
	(test -f ./database/database.sqlite3 || uv run fastmigrate_create_db)
	uv run fastmigrate_run_migrations
}

function run_serve(){
	uv run fastmigrate_run_migrations
	uv run app/main.py
}

function run_stop(){
	# By default the application runs on port 5001.
	# This command finds applications running on port 5001 and
	# kills them.
	lsof -i :5001 | awk '{print $2}' | tail -n +2 | xargs kill
}

function run_lint(){
	uv run ruff check
}

function run_unit(){
	uv run pytest tests/
}

function main(){
	cmd=${1-default}
	shift || true
	case "$cmd" in
		default|help)
			help "$@"
			;;
		restore)
			run_restore
			;;
		serve)
			run_serve
			;;
		stop)
			run_stop
			;;
		lint)
			run_lint
			;;
		unit)
			run_unit
			;;
		*)
			echo "no-op $cmd"
			;;
	esac
}

main "$@"
