"""add indexes to users and usernotes

Revision ID: 18d079fc67cc
Revises: 4715e91f2e09
Create Date: 2026-03-01 18:54:04.045554

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

from app.models import *


# revision identifiers, used by Alembic.
revision: str = '18d079fc67cc'
down_revision: Union[str, Sequence[str], None] = '4715e91f2e09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_id'), ['id'], unique=False)

    with op.batch_alter_table('usernote', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usernote_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usernote', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usernote_id'))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_id'))

    # ### end Alembic commands ###
