"""remove redundant indexes on user and usernote

Revision ID: 19ff788acae9
Revises: 18d079fc67cc
Create Date: 2026-09-17 15:43:56.274050

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

from app.models import *


# revision identifiers, used by Alembic.
revision: str = '19ff788acae9'
down_revision: Union[str, Sequence[str], None] = '18d079fc67cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_id'))

    with op.batch_alter_table('usernote', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usernote_id'))
        batch_op.create_foreign_key('fk_usernote_user_added_by_user_id', 'user', ['note_added_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usernote', schema=None) as batch_op:
        batch_op.drop_constraint('fk_usernote_user_added_by_user_id', type_='foreignkey')
        batch_op.create_index(batch_op.f('ix_usernote_id'), ['id'], unique=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_id'), ['id'], unique=False)

    # ### end Alembic commands ###
