"""init

Revision ID: 2c93f737c2d1
Revises: 
Create Date: 2026-02-28 22:43:32.222653

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

from app.models import *


# revision identifiers, used by Alembic.
revision: str = '2c93f737c2d1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('gh_login', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('gh_node_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('gh_avatar_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('gh_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('gh_created_at', sa.DateTime(), nullable=False),
    sa.Column('creation_date', sa.DateTime(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usernote',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('note_added_by', sa.Integer(), nullable=False),
    sa.Column('note', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usernote')
    op.drop_table('user')
    # ### end Alembic commands ###
