"""test

Revision ID: 4715e91f2e09
Revises: 2c93f737c2d1
Create Date: 2026-03-01 14:52:13.794876

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

from app.models import *


# revision identifiers, used by Alembic.
revision: str = '4715e91f2e09'
down_revision: Union[str, Sequence[str], None] = '2c93f737c2d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usernote', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'user', ['note_added_by'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usernote', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
