"""add foreign key to user notes

Revision ID: c2e7a4e9eccf
Revises: 2c93f737c2d1
Create Date: 2026-02-28 23:52:07.669410

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

from app.models import *


# revision identifiers, used by Alembic.
revision: str = 'c2e7a4e9eccf'
down_revision: Union[str, Sequence[str], None] = '2c93f737c2d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'usernote', 'user', ['note_added_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'usernote', type_='foreignkey')
    # ### end Alembic commands ###
