#!/usr/bin/env bash

set -euo pipefail
THISDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

function help(){
cat << EOF
prod-deploy

help         : Display help text
deploy <sha> : Deploy version
EOF
}

function run_deploy(){
	cd "$THISDIR/.."
	CURRENT_SHA=$(git rev-parse --short HEAD)
	CURRENT_SHA="${CURRENT_SHA:-no_sha}"
	CURRENT_TAG=$(git tag --points-at HEAD)
	CURRENT_TAG="${CURRENT_TAG:-no_tag}"

	# Stop the service
	./run stop

	# Take backup of data store
	mkdir -p database/backups
	cp database/database.sqlite3 \
		"database/backups/$CURRENT_TAG-$CURRENT_SHA.database.sqlite3"

	# Checkout the tag
	git checkout "$1"
	
	# Restore environment and serve
	./run restore
	./run serve
}

function main(){
	cmd=${1-default}
	shift || true
	case "$cmd" in
		default|help)
			help "$@"
			;;
		deploy)
			run_deploy "$@"
			;;
		*)
			echo "no-op $cmd"
			;;
	esac
}

main "$@"
